name: guia_moteis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  expandable_page_view: ^1.0.17
  equatable: ^2.0.7
  flutter_svg: '^2.0.10+1'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
      - assets/svg/


